### ISSUE TITLE
(CompileError) lib/postgres_describe.ex:7

### ISSUE THREAD

**Issue by jasonu** [brandonparsons/postgres_describe#1]
After adding:

`{:postgres_describe, "~> 0.1.1"}`

to my `mix.exs` file and then running `mix deps.get` it fails to install the Private module from hex.pm and thus fails to build when I run `mix compile` or `mix PostgresDescribe`.

Upon commenting out the lines 7, 74 and 105 in "lib/postgres_describe.ex" it compiles. I also had to remove the leading slash, "/" in the "write_dir" field of the config block. That is:

`write_dir: "/tmp",    ==> write_dir: "tmp",`

Everything worked fine after those two changes. Also, you have a typo in your documentation for "basic config", the config has the field `pubic` which should obviously be `public`.

Thanks for the cool package!

**Comment by brandonparsons** [comment]
@jasonu  Thanks for the report!

I've pushed [`0.1.2`](https://github.com/brandonparsons/postgres_describe/commit/723612efa3b5a9a05a02f3a37dfe77a3f59553e4) which should fix _most_ of the issues above. I realized that I had limited use of the `private` library to `:dev` and `:test` which doesn't make sense as it shows up right in the library code.

For the issue you mentioned where you had to change `write_dir` to have no leading slash, could this be because the elixir process doesn't have write access to your computer's `/tmp` directory? Or are you on windows?

**Comment by jasonu** [comment]
I changed the deps function to require `"~> 0.1.2"`, ran `mix deps.get` and then ran `mix PostgresDescribe` and it worked fine with no leading slash. I then added the leading slash and ran the following in terminal:

```
jasonu@Frobenius:~/Developer/Elixir/rumbl$ rm -R tmp
jasonu@Frobenius:~/Developer/Elixir/rumbl$ mkdir tmp
jasonu@Frobenius:~/Developer/Elixir/rumbl$ chmod a+w tmp
jasonu@Frobenius:~/Developer/Elixir/rumbl$ ls -al
total 312
drwxr-xr-x   19 jasonu  staff   646B Dec 22 10:12 ./
drwxr-xr-x   11 jasonu  staff   374B Dec 21 16:56 ../
drwxr-xr-x   12 jasonu  staff   408B Dec 22 09:49 .git/
-rw-r--r--    1 jasonu  staff   570B Dec 14 14:06 .gitignore
-rw-r--r--    1 jasonu  staff   992B Dec 14 14:22 README.md
drwxr-xr-x    4 jasonu  staff   136B Dec  4 10:11 _build/
-rw-r--r--    1 jasonu  staff   1.6K Nov  4 14:11 brunch-config.js
drwxr-xr-x    7 jasonu  staff   238B Dec 22 09:58 config/
drwxr-xr-x   26 jasonu  staff   884B Dec 22 09:49 deps/
drwxr-xr-x    4 jasonu  staff   136B Dec 20 19:43 lib/
-rw-r--r--    1 jasonu  staff   1.8K Dec 22 09:49 mix.exs
-rw-r--r--    1 jasonu  staff   5.4K Dec 22 09:49 mix.lock
drwxr-xr-x  331 jasonu  staff    11K Dec  2 12:23 node_modules/
-rw-r--r--    1 jasonu  staff   125K Dec  2 12:23 package-lock.json
-rw-r--r--    1 jasonu  staff   459B Dec  2 13:15 package.json
drwxr-xr-x    5 jasonu  staff   170B Nov  4 14:12 priv/
drwxr-xr-x    8 jasonu  staff   272B Nov  4 14:11 test/
drwxrwxrwx    2 jasonu  staff    68B Dec 22 10:12 tmp/
drwxr-xr-x   11 jasonu  staff   374B Dec 14 14:55 web/
jasonu@Frobenius:~/Developer/Elixir/rumbl$ mix PostgresDescribe
jasonu@Frobenius:~/Developer/Elixir/rumbl$ ls tmp
jasonu@Frobenius:~/Developer/Elixir/rumbl$ 
```
No files were generated in the `tmp` folder even though all users have write permission.
My OS is OS X Yosemite (10.10.5).  Here are my versions of Elixir and Phoenix:

```
jasonu@Frobenius:~/Developer/Elixir/rumbl$ elixir -v
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
jasonu@Frobenius:~/Developer/Elixir/rumbl$ mix phoenix.new -v
Phoenix v1.2.4
```

**Comment by jasonu** [comment]
Everything works great now. It was late last night when I tried it and I was creating a `tmp` folder in my project's folder! The software was writing to the top level `\tmp` directory and I wasn't looking there, but it was writing the db docs there! Sorry, sometimes I'm an idiot.

**Comment by brandonparsons** [comment]
@jasonu 🤣 no problem. Glad it's all working.
